### ISSUE TITLE
插件安装后遇到的一些问题

### ISSUE THREAD

**Issue by PajamASO** [MinatoAquaCrews/nonebot_plugin_fortune#12]
根据READ_ME的教程，我安装了插件，并且下载了resource文件夹并将它放在/data路径下。也在nonebot项目下配置了.env文件，添加了FORTUNE_PATH="/data/resource"，最后还在resource/fortune_setting.json内配置了抽签规则。
但是在启动项目后还是遇到了导入失败的情况，错误记录如下：

04-13 15:46:54 [ERROR] nonebot | Failed to import "nonebot_plugin_fortune"
Traceback (most recent call last):
  File "/data/go-cqhttp/main/nonebot/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 29, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/__init__.py", line 6, in <module>
    from .data_source import fortune_manager
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/data_source.py", line 195, in <module>
    fortune_manager = FortuneManager(Path(FORTUNE_PATH))
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/data_source.py", line 46, in __init__
    self.setting = json.load(f)
ujson.JSONDecodeError: Unexpected character in found when decoding object value

希望大佬能帮我排查下错误

**Comment by KafCoppelia** [comment]
```
File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/data_source.py", line 46, in init
self.setting = json.load(f)
ujson.JSONDecodeError: Unexpected character in found when decoding object value
```
`json`配置文件的格式错了

**Comment by PajamASO** [comment]
谢谢大佬。。。。是我fortune_setting.json配置群规则少加了一个括号
