### ISSUE TITLE
运行插件时遇到的问题

### ISSUE THREAD

**Issue by Hanx152** [MinatoAquaCrews/nonebot_plugin_fortune#13]
输入抽签之后的报错，我实在不知道应该把resource文件放到哪里，如果是很低级的问题还麻烦大佬耐心指点一下我，谢谢
04-16 20:55:20 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_fortune, type=message, priority=8, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\__init__.py", line 52, in _
    image_file, status = fortune_manager.divine(spec_path=None, event=event)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\data_source.py", line 81, in divine
    image_file = drawing(theme, spec_path, user_id, group_id)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\utils.py", line 124, in drawing
    imgPath = randomBasemap(theme, spec_path)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\utils.py", line 102, in randomBasemap
    picked_theme = random.choice(os.listdir(__p))
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/data/resource/img'

**Comment by KafCoppelia** [comment]
`FORTUNE_PATH="your_path_to_resource"`，只要配置`FORTUNE_PATH`到你的`resource`文件夹就行

**Comment by Hanx152** [comment]
我配置到resource文件夹为什么还会有这样的问题呢
04-16 22:18:32 [ERROR] nonebot | Failed to import "nonebot_plugin_fortune"
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Bot2.0\gocq\Bot\.\bot.py", line 30, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\__init__.py", line 6, in <module>
    from .data_source import fortune_manager
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\data_source.py", line 10, in <module>
    from .config import FORTUNE_PATH
  File "c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_fortune\config.py", line 12
    fortune_path: str = os.path.join(os.path.dirname(__file__), "D:\Bot2.0\nonebot_plugin_fortune-0.4.3\nonebot_plugin_fortune\resource"")

**Comment by KafCoppelia** [comment]
你使用的自己的`FORTUNE_PATH`还是用插件默认的配置，看看。你`resource`文件夹所在位置也看一下

**Comment by Hanx152** [comment]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/103246532/163678711-fd2b428a-050a-4cb8-bd1b-b4ac61f72812.png">
这是resource文件
fortune_path的设置我不知道是改哪里的，我改了resource文件夹里面那个config的，还在bot文件夹里面那个env prod底下加了一行

**Comment by KafCoppelia** [comment]
不用改插件代码里的，在你的`env`配置中写`FORTUNE_PATH="./data/resource`比如这种

**Comment by Hanx152** [comment]
好了好了，谢谢大佬
