### ISSUE TITLE
请问能不能自己添加图片资源

### ISSUE THREAD

**Issue by PajamASO** [MinatoAquaCrews/nonebot_plugin_fortune#15]
在resource/img下创建了一个230文件夹用于装自定义的图片，但是在抽签过程中好像出现了问题：

05-15 21:35:11 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_fortune, type=message, priority=8, temp=False> failed.
Traceback (most recent call last):
  File "/data/go-cqhttp/main/nonebot/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/__init__.py", line 52, in _
    image_file, status = fortune_manager.divine(spec_path=None, event=event)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/data_source.py", line 81, in divine
    image_file = drawing(theme, spec_path, user_id, group_id)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/utils.py", line 124, in drawing
    imgPath = randomBasemap(theme, spec_path)
  File "/data/go-cqhttp/main/nonebot/lib/python3.8/site-packages/nonebot_plugin_fortune/utils.py", line 103, in randomBasemap
    if MainThemeEnable[picked_theme] == True:
KeyError: '230'

请问是不是因为自定义图片大小不合格，还是说要在某个配置文件中进行申请才能使用？

**Comment by KafCoppelia** [comment]
[How-to-add-new-theme](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/blob/beta/How-to-add-new-theme.md) 同样适用于添加自定义的主题资源
关于图片大小，我记得目前所有主题资源都是480*480，应该需要在`utils`下`def drawing()`里`Image.open()`后resize成480*480

**Comment by PajamASO** [comment]
试了下好像还有同样的问题，应该是图片大小不合格导致的。
