### ISSUE TITLE
nonebot无法导入nonebot_plugin_fortune

### ISSUE THREAD

**Issue by yukuka520** [MinatoAquaCrews/nonebot_plugin_fortune#17]
通过nb安装后直接运行`bot.py`文件出现下面报错，也下载替换了`resource`文件夹中的文件，同时也按照教程的步骤做了几遍，卸载安装后也是这样，也尝试把`resource`里面的文件移到其他地方，还是这样报错
```
06-18 18:31:03 [ERROR] nonebot | Failed to import "nonebot_plugin_fortune"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QQ_BOT\nb2\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_fortune\__init__.py", line 6, in <module>
    from .data_source import fortune_manager
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_fortune\data_source.py", line 195, in <module>
    fortune_manager = FortuneManager(Path(FORTUNE_PATH))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_fortune\data_source.py", line 46, in __init__
    self.setting = json.load(f)
ujson.JSONDecodeError: Expected object or value
```
想问一下大佬怎么解决

**Comment by KafCoppelia** [comment]
`fortune_setting.json`文件在吗，内容是什么样的

**Comment by yukuka520** [comment]
我看了其他的issues，已经解决了

**Comment by yukuka520** [comment]
这样的
```
{
    "group_rule": {
    },
    "specific_rule": {
        "艾雅法拉": [
            "arknights\/艾雅法拉.jpg"
        ],
        "小羊": [
            "arknights\/艾雅法拉.jpg"
        ],
        "安洁莉娜": [
            "arknights\/安洁莉娜.jpg"
        ],
        "杰哥": [
            "arknights\/安洁莉娜.jpg"
        ],
        "陈": [
            "arknights\/陈.jpg"
        ],
        "肠粉龙": [
            "arknights\/陈.jpg"
        ],
        "陈晖洁": [
            "arknights\/陈.jpg"
        ],
        "初雪": [
            "arknights\/初雪.jpg"
        ],
        "风笛": [
            "arknights\/风笛.jpg"
        ],
        "傀影": [
            "arknights\/傀影.jpg"
        ],
        "赫拉格": [
            "arknights\/赫拉格.jpg"
        ],
        "老爷子": [
            "arknights\/赫拉格.jpg"
        ],
        "黑": [
            "arknights\/黑.jpg"
        ],
        "煌": [
            "arknights\/煌.jpg"
        ],
        "棘刺": [
            "arknights\/棘刺.jpg"
        ],
        "刻俄柏": [
            "arknights\/刻俄柏.jpg"
        ],
        "小刻": [
            "arknights\/刻俄柏.jpg"
        ],
        "空弦": [
            "arknights\/空弦.jpg"
        ],
        "铃兰": [
            "arknights\/铃兰.jpg"
        ],
        "麦哲伦": [
            "arknights\/麦哲伦.jpg"
        ],
        "小企鹅": [
            "arknights\/麦哲伦.jpg"
        ],
        "企鹅": [
            "arknights\/麦哲伦.jpg"
        ],
        "莫斯提马": [
            "arknights\/莫斯提马.jpg"
        ],
        "蓝天使": [
            "arknights\/莫斯提马.jpg"
        ],
        "能天使": [
            "arknights\/能天使.jpg"
        ],
        "泥岩": [
            "arknights\/泥岩.jpg"
        ],
        "年": [
            "arknights\/年.jpg"
        ],
        "塞雷娅": [
            "arknights\/塞雷娅.jpg"
        ],
        "森蚺": [
            "arknights\/森蚺.jpg"
        ],
        "闪灵": [
            "arknights\/闪灵.jpg"
        ],
        "史尔特尔": [
            "arknights\/史尔特尔.jpg"
        ],
        "斯卡蒂": [
            "arknights\/斯卡蒂.jpg"
        ],
        "蒂蒂": [
            "arknights\/斯卡蒂.jpg"
        ],
        "推进之王": [
            "arknights\/推进之王.jpg"
        ],
        "推王": [
            "arknights\/推进之王.jpg"
        ],
        "王小姐": [
            "arknights\/推进之王.jpg"
        ],
        "温蒂": [
            "arknights\/温蒂.jpg"
        ],
        "霞光": [
            "arknights\/霞光.jpg"
        ],
        "星熊": [
            "arknights\/星熊.jpg"
        ],
        "夜莺": [
            "arknights\/夜莺.jpg"
        ],
        "伊芙利特": [
            "arknights\/伊芙利特.jpg"
        ],
        "小火龙": [
            "arknights\/伊芙利特.jpg"
        ],
        "银灰": [
            "arknights\/银灰.jpg"
        ],
        "银老板": [
            "arknights\/银灰.jpg"
        ],
        "早露": [
            "arknights\/早露.jpg"
        ],
        "W": [
            "arknights\/W.jpg"
        ],
        "向晚": [
            "asoul\/Ava-Q.jpg",
            "asoul\/Ava.jpg"
        ],
        "贝拉": [
            "asoul\/Bella-Q.jpg",
            "asoul\/Bella.jpg"
        ],
        "珈乐": [
            "asoul\/Carol-Q.jpg",
            "asoul\/Carol.jpg"
        ],
        "嘉然": [
            "asoul\/Diana-Q.jpg",
            "asoul\/Diana.jpg"
        ],
        "乃琳": [
            "asoul\/Eileen-Q.jpg",
            "asoul\/Eileen.jpg"
        ],
        "迪奥娜": [
            "genshin\/frame_1.jpg"
        ],
        "芭芭拉": [
            "genshin\/frame_2.jpg"
        ],
        "魈": [
            "genshin\/frame_3.jpg"
        ],
        "重云": [
            "genshin\/frame_4.jpg"
        ],
        "行秋": [
            "genshin\/frame_5.jpg"
        ],
        "凯亚": [
            "genshin\/frame_6.jpg"
        ],
        "雷泽": [
            "genshin\/frame_7.jpg"
        ],
        "温迪": [
            "genshin\/frame_8.jpg"
        ],
        "班尼特": [
            "genshin\/frame_9.jpg"
        ],
        "迪卢克": [
            "genshin\/frame_10.jpg"
        ],
        "砂糖": [
            "genshin\/frame_11.jpg"
        ],
        "北斗": [
            "genshin\/frame_12.jpg"
        ],
        "菲谢尔": [
            "genshin\/frame_13.jpg"
        ],
        "诺艾尔": [
            "genshin\/frame_14.jpg"
        ],
        "香菱": [
            "genshin\/frame_15.jpg"
        ],
        "达达利亚": [
            "genshin\/frame_16.jpg"
        ],
        "丽莎": [
            "genshin\/frame_17.jpg"
        ],
        "安柏": [
            "genshin\/frame_18.jpg"
        ],
        "七七": [
            "genshin\/frame_19.jpg"
        ],
        "琴": [
            "genshin\/frame_20.jpg"
        ],
        "凝光": [
            "genshin\/frame_21.jpg"
        ],
        "莫娜": [
            "genshin\/frame_22.jpg"
        ],
        "刻晴": [
            "genshin\/frame_23.jpg"
        ],
        "可莉": [
            "genshin\/frame_24.jpg"
        ],
        "钟离": [
            "genshin\/frame_25.jpg"
        ],
        "辛焱": [
            "genshin\/frame_26.jpg"
        ],
        "阿贝多": [
            "genshin\/frame_27.jpg"
        ],
        "时乃空": [
            "hololive\/frame_1.jpg"
        ],
        "空妈": [
            "hololive\/frame_1.jpg"
        ],
        "友人A": [
            "hololive\/frame_2.jpg"
        ],
        "AZKi": [
            "hololive\/frame_3.jpg"
        ],
        "亚绮·罗森塔尔": [
            "hololive\/frame_4.jpg"
        ],
        "萝卜子": [
            "hololive\/frame_5.jpg"
        ],
        "夏色祭": [
            "hololive\/frame_6.jpg"
        ],
        "佐藤希": [
            "hololive\/frame_6.jpg"
        ],
        "桐生可可": [
            "hololive\/frame_7.jpg"
        ],
        "花咲雅": [
            "hololive\/frame_8.jpg"
        ],
        "角卷绵芽": [
            "hololive\/frame_9.jpg"
        ],
        "紫咲诗音": [
            "hololive\/frame_10.jpg"
        ],
        "常暗永远": [
            "hololive\/frame_11.jpg"
        ],
        "赤井心": [
            "hololive\/frame_12.jpg"
        ],
        "大空昴": [
            "hololive\/frame_13.jpg"
        ],
        "大神澪": [
            "hololive\/frame_14.jpg"
        ],
        "天音彼方": [
            "hololive\/frame_15.jpg"
        ],
        "白银诺艾尔": [
            "hololive\/frame_16.jpg"
        ],
        "白上吹雪": [
            "hololive\/frame_17.jpg"
        ],
        "fbk": [
            "hololive\/frame_17.jpg"
        ],
        "凑阿库娅": [
            "hololive\/frame_18.jpg"
        ],
        "阿夸": [
            "hololive\/frame_18.jpg"
        ],
        "夜空梅露": [
            "hololive\/frame_19.jpg"
        ],
        "李清歌": [
            "liqingge\/1.png",
            "liqingge\/2.png",
            "liqingge\/3.png",
            "liqingge\/4.png",
            "liqingge\/5.png",
            "liqingge\/6.png",
            "liqingge\/7.png",
            "liqingge\/8.png",
            "liqingge\/9.png",
            "liqingge\/10.png",
            "liqingge\/11.png",
            "liqingge\/12.png",
            "liqingge\/13.png",
            "liqingge\/14.png",
            "liqingge\/15.png",
            "liqingge\/16.png"
        ],
        "彼岸花": [
            "onmyoji\/彼岸花.jpg"
        ],
        "椒图": [
            "onmyoji\/椒图.jpg"
        ],
        "青行灯": [
            "onmyoji\/青行灯1.jpg",
            "onmyoji\/青行灯2.jpg"
        ],
        "神乐": [
            "onmyoji\/神乐.jpg"
        ],
        "桃花妖": [
            "onmyoji\/桃花妖.jpg"
        ],
        "雪女": [
            "onmyoji\/雪女1.jpg",
            "onmyoji\/雪女2.jpg",
            "onmyoji\/雪女3.jpg"
        ],
        "樱花妖": [
            "onmyoji\/樱花妖.jpg"
        ],
        "莹草": [
            "onmyoji\/莹草.jpg"
        ],
        "博丽灵梦": [
            "touhou\/frame_1.jpg"
        ],
        "灵梦": [
            "touhou\/frame_1.jpg"
        ],
        "雾雨魔理沙": [
            "touhou\/frame_2.jpg"
        ],
        "魔理沙": [
            "touhou\/frame_2.jpg"
        ],
        "妖梦": [
            "touhou\/frame_3.jpg"
        ],
        "芙兰朵露": [
            "touhou\/frame_4.jpg"
        ],
        "二小姐": [
            "touhou\/frame_4.jpg"
        ],
        "蕾米莉亚": [
            "touhou\/frame_5.jpg"
        ],
        "西行寺幽幽子": [
            "touhou\/frame_6.jpg"
        ],
        "幽幽子": [
            "touhou\/frame_6.jpg"
        ],
        "八云紫": [
            "touhou\/frame_7.jpg"
        ],
        "铃仙": [
            "touhou\/frame_8.jpg",
            "touhou\/frame_14.jpg"
        ],
        "琪露诺": [
            "touhou\/frame_9.jpg"
        ],
        "大妖精": [
            "touhou\/frame_10.jpg"
        ],
        "桑尼米尔克": [
            "touhou\/frame_11.jpg"
        ],
        "莉莉怀特": [
            "touhou\/frame_12.jpg"
        ],
        "莉莉白": [
            "touhou\/frame_12.jpg"
        ],
        "露娜切露德": [
            "touhou\/frame_13.jpg"
        ],
        "红美玲": [
            "touhou\/frame_15.jpg"
        ],
        "十六夜咲夜": [
            "touhou\/frame_16.jpg"
        ],
        "咲夜": [
            "touhou\/frame_16.jpg"
        ]
    }
}
```

**Comment by KafCoppelia** [comment]
额那应该没问题吧

**Comment by yukuka520** [comment]
我重新运行N次，然后解决了，好奇怪
