### ISSUE TITLE
TypeError: expected string以前我记得我解决过后来再装又出这个问题了

### ISSUE THREAD

**Issue by smallka1** [MinatoAquaCrews/nonebot_plugin_fortune#41]
09-23 23:03:43 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_fortune, type=message, priority=8, temp=False> failed.
Traceback (most recent call last):
  File "d:\robot\2\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 262, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 146, in _check_matcher        
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__ 
    return await self.call(**values)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_fortune\__init__.py", line 52, in _      
    image_file, status = fortune_manager.divine(spec_path=None, event=event)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_fortune\data_source.py", line 81, in divine
    image_file = drawing(theme, spec_path, user_id, group_id)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_fortune\utils.py", line 135, in drawing  
    font_length = ttfront.getsize(title)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 483, in getsize
    size, offset = self.font.getsize(text, "L", direction, features, language)
TypeError: expected string

**Comment by smallka1** [comment]
resource里的font文件夹吗还是指什么，font里有sakura.ttf和Mamelon.otf

**Comment by KafCoppelia** [comment]
根据
https://github.com/python-pillow/Pillow/issues/3066
https://github.com/PaddlePaddle/PaddleOCR/issues/1603
试试重装一下Pillow

**Comment by smallka1** [comment]
我去全部重装一下试试看

**Comment by smallka1** [comment]
还是不太行，想放弃了

**Comment by KafCoppelia** [comment]
😭

**Comment by smallka1** [comment]
重装了pillow9.0.0版本后正常使用了
