### ISSUE TITLE
【报错】运行插件时出现问题……

### ISSUE THREAD

**Issue by BMC-Gordon0921** [MinatoAquaCrews/nonebot_plugin_fortune#49]
在使用插件的时候遇到了一些问题，希望大佬们可以指点一二；如果是很白痴或者和插件本身无关的问题，还请大佬们浇浇我这只刚刚踏进nonebot的小萌新，让我去多吃点网上的资料和教程（磕头跪谢）
以下是问题报告：
环境：Ubuntu22.04（LTS），Python3.9.8，nonebot-2.0.0rc1，nonebot_plugin_apscheduler==0.1.4，nonebot_plugin_fortune（本插件）==0.4.9

问题描述：运行bot.py后控制台报错，使用`nb run`指令也是报错的。和另外一些使用nonebot_plugin_apscheduler等包含定时任务的插件一样，在我的WindowsPC上跑的好好的，指令正常捕获并且有反应，上了Ubuntu直接爆红（晕）

问题初步分析：看了错误代码和百度翻译（误），初步定位到的问题应该是linux（Ubuntu）下的apscheduler时区错误，以至于nonebot_plugin_apscheduler插件报错，牵连导致所有使用该插件的第三方库一起掉坑（）

报错详细信息：
```
11-13 12:30:59 [ERROR] nonebot | Failed to import "nonebot_plugin_apscheduler"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_compat_py3.py", line 16, in get_timezone
    return zoneinfo.ZoneInfo(key)
  File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 67, in find_tzfile
    _validate_tzfile_path(key)
  File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 91, in _validate_tzfile_path
    raise ValueError(
ValueError: ZoneInfo keys must be normalized relative paths, got: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_impl.py", line 39, in timezone
    zone = _compat.get_timezone(key)
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_compat_py3.py", line 19, in get_timezone
    raise KeyError(key)
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/??/bot_linux/bot.py", line 29, in <module>
    nonebot.load_plugin('nonebot_plugin_fortune')
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_fortune/__init__.py", line 12, in <module>
    require("nonebot_plugin_apscheduler")
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 165, in require
    plugin = load_plugin(name)
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_apscheduler/__init__.py", line 13, in <module>
    scheduler = AsyncIOScheduler()
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 131, in configure
    self._configure(config)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/asyncio.py", line 54, in _configure
    super(AsyncIOScheduler, self)._configure(config)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 180, in _get_localzone
    tz = pds.timezone(tzname)
  File "/usr/local/lib/python3.9/site-packages/pytz_deprecation_shim/_impl.py", line 41, in timezone
    raise get_exception(UnknownTimeZoneError, key)
pytz_deprecation_shim._exceptions._make_pytz_derived_errors.<locals>.UnknownTimeZoneError: ''
11-13 12:30:59 [ERROR] nonebot | Failed to import "nonebot_plugin_fortune"
Traceback (most recent call last):
  File "/root/??/bot_linux/bot.py", line 29, in <module>
    nonebot.load_plugin('nonebot_plugin_fortune')
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_fortune/__init__.py", line 12, in <module>
    require("nonebot_plugin_apscheduler")
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 167, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!
```

**Comment by KafCoppelia** [comment]
检查一下硬件UTC时区，再看下[nonebot_plugin_apscheduler](https://github.com/nonebot/plugin-apscheduler)的说明

**Comment by BMC-Gordon0921** [comment]
> 检查一下硬件UTC时区，再看下[nonebot_plugin_apscheduler](https://github.com/nonebot/plugin-apscheduler)的说明

佬，在nonebot_plugin_apscheduler/__init__.py

**Comment by BMC-Gordon0921** [comment]
谢谢佬的教程——（开心）
修改nonebot_plugin_apscheduler/__init__.py中
`scheduler = AsyncIOScheduler()`
成为
`scheduler = AsyncIOScheduler(){
    "apscheduler.timezone": "Asia/Shanghai" 
    }`
以后，问题得到解决，插件成功运行 ：）
对了，要先在pip里面升级nonebot_plugin_apscheduler到0.2.0版本
佬快快放宽本插件对于apscheduler的版本要求鸭！

**Comment by KafCoppelia** [comment]
时区参见nb2指南[定时任务](https://v2.nonebot.dev/docs/advanced/scheduler)部分
`nonebot_plugin_apscheduler`其实`v0.1.4`也行，这个定时插件在`v0.2.0`是破坏性更新，因此还未适配
