### ISSUE TITLE
按照文档配置报错ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by silverlinin9** [MinatoAquaCrews/nonebot_plugin_fortune#61]
按照文档中方式配置，nb run启动机器人时出现如下错误
02-23 15:19:51 [ERROR] nonebot | Failed to import "nonebot_plugin_fortune"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot_plugin_fortune\__init__.py", line 9, in <module>
    from .data_source import fortune_manager
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot_plugin_fortune\data_source.py", line 6, in <module>
    from .config import fortune_config, FortuneThemesDict, DateTimeEncoder
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot_plugin_fortune\config.py", line 8, in <module>
    from .download import ResourceError, download_resource
  File "C:\Users\Lenovo\Desktop\robot\Atom\.venv\lib\site-packages\nonebot_plugin_fortune\download.py", line 5, in <module>
    import aiofiles
ValueError: source code string cannot contain null bytes

**Comment by silverlinin9** [comment]
python3.10.9

**Comment by KafCoppelia** [comment]
> ValueError: source code string cannot contain null bytes

编码问题？

**Comment by silverlinin9** [comment]
都确定.py文件是utf-8

**Comment by silverlinin9** [comment]
json也是

**Comment by KafCoppelia** [comment]
我感觉是Pycharm的锅，我开发环境在vscode。印象中，Pycharm开发的代码在vscode下有些编码问题，也许反过来也是……

**Comment by silverlinin9** [comment]
那star一下，期待v 0.5.0

**Comment by KafCoppelia** [comment]
难产了已经，在搞项目……

**Comment by KafCoppelia** [comment]
请尝试一下更新的版本。如仍有问题可reopen.
