### ISSUE TITLE
加载插件出错

### ISSUE THREAD

**Issue by NanakoOfficial** [MinatoAquaCrews/nonebot_plugin_fortune#64]
```
03-26 18:52:01 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 612, in startup
    await handler()
  File "D:\Desktop\0\software\IRONY-Bot-main\IRONY-Bot\src\plugins\nonebot_plugin_fortune\config.py", line 126, in fortune_check
    ret = await download_resource(copywriting_path, "copywriting.json", "fortune")
  File "D:\Desktop\0\software\IRONY-Bot-main\IRONY-Bot\src\plugins\nonebot_plugin_fortune\download.py", line 47, in download_resource
    version = resp.json().get("version")
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Demo\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

大佬求解

**Comment by Arymodu** [comment]
今天我也是突然这样，一样的报错，自己调试了好久没解决

**Comment by NanakoOfficial** [comment]
> 今天我也是突然这样，一样的报错，自己调试了好久没解决

本人已解决，我的方法如下
把文件夹里download.py里

base_url: str = "https://raw.fastgit.org/MinatoAquaCrews/nonebot_plugin_fortune/master/nonebot_plugin_fortune/resource

链接替换为

https://raw.githubusercontent.com/MinatoAquaCrews/nonebot_plugin_fortune/master/nonebot_plugin_fortune/resource

你试试可不可以恢复正常

**Comment by Arymodu** [comment]
> 

已解决，感谢

**Comment by Arymodu** [comment]
> > 今天我也是突然这样，一样的报错，自己调试了好久没解决
> 
> 本人已解决，我的方法如下 把文件夹里download.py里
> 
> base_url: str = "https://raw.fastgit.org/MinatoAquaCrews/nonebot_plugin_fortune/master/nonebot_plugin_fortune/resource
> 
> 链接替换为
> 
> https://raw.githubusercontent.com/MinatoAquaCrews/nonebot_plugin_fortune/master/nonebot_plugin_fortune/resource
> 
> 你试试可不可以恢复正常

已解决，感谢

**Comment by KafCoppelia** [comment]
那问题似乎是 `raw.fastgit.org` 下载不行了？

**Comment by NanakoOfficial** [comment]
> 那问题似乎是 `raw.fastgit.org` 下载不行了？

应该是，我这边测试是访问不了了

**Comment by Wexevou** [comment]
你这边会不会今日运势生成出错 能不能看看你的.env配置 我配置了也是这样

**Comment by NanakoOfficial** [comment]
> 你这边会不会今日运势生成出错 我按照你这样修复后 就这样了 能不能看看你的.env配置 我配置了也是这样

我没报错过呀，你.env的资源文件夹路径写对了没

我的是

`FORTUNE_PATH="./D:/Desktop/0/software/IRONY-Bot-main/IRONY-Bot/src/plugins/nonebot_plugin_fortune/resource"`

**Comment by Wexevou** [comment]
> > 你这边会不会今日运势生成出错 我按照你这样修复后 就这样了 能不能看看你的.env配置 我配置了也是这样
> 
> 我没报错过呀，你.env的资源文件夹路径写对了没
> 
> 我的是
> 
> `FORTUNE_PATH="./D:/Desktop/0/software/IRONY-Bot-main/IRONY-Bot/src/plugins/nonebot_plugin_fortune/resource"`

那我也这样试试

**Comment by KafCoppelia** [comment]
> > > 你这边会不会今日运势生成出错 我按照你这样修复后 就这样了 能不能看看你的.env配置 我配置了也是这样
> > 
> > 
> > 我没报错过呀，你.env的资源文件夹路径写对了没
> > 我的是
> > `FORTUNE_PATH="./D:/Desktop/0/software/IRONY-Bot-main/IRONY-Bot/src/plugins/nonebot_plugin_fortune/resource"`
> 
> 那我也这样试试

呃呃呃呃，路径不要模仿别人的呀，每个人的文件路径都不一样的

**Comment by Wexevou** [comment]
> > > > 你这边会不会今日运势生成出错 我按照你这样修复后 就这样了 能不能看看你的.env配置 我配置了也是这样
> > > 
> > > 
> > > 我没报错过呀，你.env的资源文件夹路径写对了没
> > > 我的是
> > > `FORTUNE_PATH="./D:/Desktop/0/software/IRONY-Bot-main/IRONY-Bot/src/plugins/nonebot_plugin_fortune/resource"`
> > 
> > 
> > 那我也这样试试
> 
> 呃呃呃呃，路径不要模仿别人的呀，每个人的文件路径都不一样的

新问题
![图片](https://user-images.githubusercontent.com/117566653/227788544-2f585b5f-4b64-4eab-a774-082e1eb0b080.png)
